// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqkctzjyqmafpytvdepf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxa2N0emp5cW1hZnB5dHZkZXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyNzM0ODQsImV4cCI6MjA5NDg0OTQ4NH0.TQMdEF3CM16vC6NEznZk50GSfEIqNflIpXVQQvN04gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});